#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/post-rewrite
# @brief A git hook script for the `post-rewrite` hook. It is called when running commands
#   that rewrite commits (e.g. git pull origin master --rebase)
# @arg $1 Denotes the command it was invoked by: currently one of amend or rebase

task git:hook:post-rewrite
