#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/post-merge
# @brief A git hook script for the `post-merge` hook
# @arg $1 A status flag specifying whether or not the merge being done was a squash merge

task git:hook:post-merge
