#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/post-update
# @brief A git hook script for the `post-update` hook

echo "[debug] post-update - param 1: $1"
echo "[debug] param 2: $2"
echo "[debug] param 3: $3"
echo "[debug] param 4: $4"
echo "[params] $GIT_PARAMS"
task git:hook:post-update
