#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/post-merge
# @brief A git hook script for the `post-merge` hook

echo "[debug] post-merge - param 1: $1"
echo "[debug] post-merge - param 2: $2"
echo "[debug] post-merge - param 3: $3"
echo "[debug] post-merge - param 4: $4"
echo "[params] $GIT_PARAMS"
task git:hook:post-merge
