#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/prepare-commit-msg
# @brief A git hook script for the `prepare-commit-msg` hook
# @arg $1 string The full path to the MERGE_MSG
# @arg $2 string The type of the `prepare-commit-msg` event. For a `git pull origin master`
# command, the event type is 'merge'.

if [ "$2" != 'merge' ]; then
  echo 'Opening a `git commit` dialog'
  exec < /dev/tty && git cz --hook || true
fi
