---
version: '3'

tasks:
  finish:
    log:
      error: Failed to finish update process
      start: Continuing the update process
      success: Finished the final stage of the update process
    cmds:
      - task: :start
      - task: :ci:commit
      - task: :ci:synchronize

  init:
    log:
      error: Error encountered while initializing the update process
      start: Initializing the update process
      success: Finished initializing the update process
    cmds:
      - task: :ci:before
      - task: :ci:submodules
      - task: :repair

  prereqs:
    log:
      error: Error encountered while installing pre-requisite software
      start: Ensuring pre-requisite software is installed and added to the PATH
      success: Pre-requisite software is installed
    cmds:
      - task: :install:software:jq
      - task: :install:software:yq
      - task: :install:software:node
      - task: :install:software:go
      - task: :install:software:poetry
