#!/bin/bash

# This file loops through all the folders that are two levels deep
# in the ./roles folder that is in the base of this repository.

if [[ -d "$PWD/roles" ]]; then
	find "$PWD/roles" -mindepth 2 -maxdepth 2 -type d -not -path '*/\.*' | while read -r FOLDER; do
		echo "Changing directory to $FOLDER"
		cd "$FOLDER" || exit
		if test -f .blueprint.json; then
			rm -rf .modules
			rm -f ansible.cfg
			rm -f package.json
			rm -f package-lock.json
			ROLE_NAME=$(basename "$PWD")
			echo "{\"version\": \"1.0.0\", \"blueprint\": {\"description\": \"""$(yq e '.galaxy_info.description' meta/main.yml)""\", \"overview\": \"""$(jq -r '.role_description_full_overview' .blueprint.json)""\", \"name\": \"""$(jq -r '.role_pretty_name' .blueprint.json)""\", \"repository\": {\"github\": \"https://github.com/ProfessorManhattan/ansible-""$ROLE_NAME""\", \"gitlab\": \"https://gitlab.com/megabyte-labs/ansible-roles/""$ROLE_NAME""\"}, \"slug\": \"""$ROLE_NAME""\", \"title\": \"""$(jq -r '.role_pretty_name' .blueprint.json)""\"}}" > package.json
			rm -f .gitmodules
			rm -f .gitlab-ci.yml
			rm -f .blueprint.json
			rm -f tests/ansible.cfg
			rm -f tests/inventory
			# rm -f tests/inventory-windows
			rm -f tests/test.yml
			# rm -f tests/windows-test.sh
			cp ~/androidstudio/.start.sh .start.sh
		else
			echo "Missing files in $FOLDER"
		fi
	done
else
	echo "ERROR: This script should be run from the root of the repository where the roles directory resides."
fi
