#!/bin/bash

# This file loops through all the folders that are two levels deep
# in the ./roles folder that is in the base of this repository.

if [[ -d "$PWD/roles" ]]; then
	find "$PWD/roles" -mindepth 2 -maxdepth 2 -type d -not -path '*/\.*' | while read -r FOLDER; do
		echo "Changing directory to $FOLDER"
		cd "$FOLDER" || exit
		rm -f ansible.cfg
	done
else
	echo "ERROR: This script should be run from the root of the repository where the roles directory resides."
fi
