#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/post-rewrite
# @brief A git hook script for the `post-rewrite` hook

echo "[debug] post-rewrite - param 1: $1"
echo "[debug] post-rewrite - param 2: $2"
echo "[debug] post-rewrite - param 3: $3"
echo "[debug] post-rewrite - param 4: $4"
echo "[params] $GIT_PARAMS"
task git:hook:post-rewrite
