#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/pre-receive
# @brief A git hook script for the `pre-receive` hook

echo "[debug] pre-receive - param 1: $1"
echo "[debug]  - param 2: $2"
echo "[debug] - param 3: $3"
echo "[debug]  - param 4: $4"
echo "[params] $GIT_PARAMS"
task git:hook:pre-receive
