---
- name: Create script for the rclone mount services
  ansible.windows.win_template:
    src: rclone.bat.j2
    dest: "C:\\Users\\{{ user.username }}\\.config\\rclone\\rclone-{{ mount.provider }}.bat"
  when: ansible_system == "Win32NT"

- name: Install the rclone mount services
  ansible.windows.win_command: "nssm install rclone-{{ mount.provider }} C:\\Users\\{{ user.username }}\\.config\\rclone\\rclone-{{ mount.provider }}.bat"
  args:
    chdir: C:\ProgramData\chocolatey\bin\
  when: ansible_system == "Win32NT"

- name: Start the rclone services
  ansible.windows.win_service:
    name: "rclone-{{ mount.provider }}"
    state: started
  when: ansible_system == "Win32NT"
