---
- name: Ensure PiHole directory exists
  file:
    mode: 0700
    path: /etc/pihole
    state: directory

- name: Add the PiHole configuration file
  template:
    dest: /etc/pihole/pihole-setupVars.conf
    mode: 0600
    src: pihole-setupVars.conf.j2

- name: Copy PiHole configuration
  copy:
    dest: /etc/pihole/setupVars.conf
    mode: 0600
    src: files/pihole-setupVars.conf
  register: pihole_config

- name: Check if PiHole binary is present
  stat:
    path: /usr/local/bin/pihole
  register: pihole_binary

- name: Determine whether PiHole is installed or not
  set_fact:
    pihole_installed: "{{ pihole_binary.stat.exists | default(false) }}"

- name: Download PiHole installation script
  get_url:
    dest: /tmp/pihole-install.sh
    mode: u+rw
    url: "{{ pihole_install_url }}"
  when: not pihole_installed

- name: Run the PiHole installation script
  command: /tmp/pihole-install.sh --unattended
  when: not pihole_installed
