---
- name: Ensure Megabyte Labs configuration directory exists
  file:
    mode: 0700
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config
    - ~/.config/megabytelabs

- name: "Check if {{ app_name }} has configuration stored in /root/.config/megabytelabs/wazuh"
  stat:
    path: ~/.config/megabytelabs/wazuh
  register: wazuh_config

- name: "Detect previously installed {{ app_name }} version"
  command: cat wazuh
  args:
    chdir: ~/.config/megabytelabs
  changed_when: false
  register: current_wazuh_version
  when: wazuh_config.stat.exists

- name: "Detect the latest {{ app_name }} version"
  uri:
    url: "{{ wazuh_package_page }}"
    return_content: true
  register: wazuh_release_page
  when: not wazuh_version

- name: Find the latest version
  set_fact:
    wazuh_version: "{{ wazuh_release_page.content | regex_search('-(?:\\d\\.)*\\d(?:-\\d)*.pkg') | replace ('.pkg','') | trim('-') }}"
  when: not wazuh_version

- name: "Determine whether or not the latest version of {{ app_name }}'s is already installed"
  set_fact:
    install_wazuh: "{{ (current_wazuh_version.skipped | default(false)) or \
      ((not current_wazuh_version.skipped | default(false)) and (current_wazuh_version.stdout != wazuh_version)) }}"

- name: "Ensure {{ app_name }}'s installer directory is present"
  ansible.builtin.file:
    mode: 0755
    path: "{{ wazuh_src_dir }}"
    state: directory

- name: Ensure that the older version of service file is uninstalled # noqa 503
  file:
    path: /Library/Ossec/bin/ossec-control
    state: absent
  when: install_wazuh

- name: "Ensure {{ app_name }}'s installer downloaded"
  get_url:
    url: "{{ wazuh_base_url }}wazuh-agent-{{ wazuh_version }}.pkg"
    dest: "{{ wazuh_src_dir }}/wazuh-agent-{{ wazuh_version }}.pkg"
  when: install_wazuh

- name: "Ensure {{ app_name }} is installed"
  command: installer -pkg wazuh-agent-{{ wazuh_version }}.pkg -target /
  args:
    chdir: "{{ wazuh_src_dir }}"
    creates: /Library/Ossec/bin/ossec-control
  when: install_wazuh

- name: "Save meta information about the version of {{ app_name }} that was installed"
  copy:
    dest: ~/.config/megabytelabs/wazuh
    mode: 0600
    content: |
      {{ wazuh_version }}
  when: install_wazuh

- name: Run generic Linux tasks
  include_tasks: config-Linux.yml
  when: wazuh_manager_ip
