---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures Wazuh is installed
# Installs Wazuh on Archlinux, CentOS, Debian, Fedora, Ubuntu, MacOS and Windows
# @action Ensures Wazuh is configured
# Registers the agent with Wazuh manager
# @action Ensures Wazuh is configured
# Enables communication with Wazuh manager
# @action Ensures Wazuh is configured
# Starts Wazuh agent service
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
