---
- name: Ensure ~/.config/rclone is a directory
  become_user: "{{ user.username }}"
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config
    - ~/.config/rclone
  when: user.rclone is defined

- name: Add rclone configuration file to ~/.config/rclone
  become_user: "{{ user.username }}"
  ansible.windows.win_template:
    src: rclone.conf.j2
    dest: ~/.config/rclone/rclone.conf
  when: user.rclone is defined

- name: Ensure ~/Documents folder exists
  become_user: "{{ user.username }}"
  ansible.windows.win_file:
    path: ~/Documents
    state: directory
  when: user.rclone is defined

- name: Mount the rclone drives
  include_tasks: mount-Windows.yml
  loop: "{{ user.rclone | default([]) }}"
  loop_control:
    label: "{{ mount.name }}"
    loop_var: mount
