---
# Default public key to add to authorized_keys
authorized_key_file: id_rsa_local.pub

certbot_admin_email: '{{ alerts_email }}'
certbot_certs:
  - email: '{{ cloudflare_email }}'
    domains:
      - '*.megabyte.space'
      - '*.home.megabyte.space'
      - '*.lab.megabyte.space'

dns_provider: 10.0.0.1#pfsense.lab.megabyte.space
dns_fallback_provider: 10.0.0.1#pfsense.lab.megabyte.space

docker_users:
  - "{{ ansible_user | default(lookup('env', 'USER')) }}"

# Repository URLs will start with this string - this makes HTTPS calls to apt-cacher-ng cachable
https_repository_prefix: http://HTTPS///

# A map of netdata rooms that are joinable (generate your own keys on https://app.netdata.cloud/
# and also get your API key for this feature to work)
_netdata_rooms:
  do: 0f7a2d28-77c0-4eb1-970b-22405a3886f7
  general: fb8e46ae-4354-454a-b676-46cda89c2e9b
  james: 495e99ef-60b4-43a4-bb60-4e05accf58a2

netdata_rooms:
  cloud: '{{ _netdata_rooms.do }}'
  guest: '{{ _netdata_rooms.james }}'
  iot: '{{ _netdata_rooms.james }}'
  kubernetes: '{{ _netdata_rooms.james }}'
  management: '{{ _netdata_rooms.james }}'
  offline: '{{ _netdata_rooms.james }}'
  unifi: '{{ _netdata_rooms.james }}'
  work: '{{ _netdata_rooms.james }}'

# The version of NodeJS to install
nodejs_version: 16.x

security_autoupdate_mail_to: '{{ alerts_email }}'
security_default_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
security_sudoers_passworded:
  - "{{ ansible_user | default(lookup('env', 'USER')) }}"
