#!/bin/sh

# @file .config/husky/pre-push
# @brief A git hook script for the `pre-push` hook
# @arg $1 The name of the remote (e.g. origin)
# @arg $2 The location of the remote (e.g. git@gitlab.com:megabyte-labs/common/angular.git)

if [ -f "$(dirname "$0")/_/husky.sh" ]; then
  . "$(dirname "$0")/_/husky.sh"
  task git:hook:pre-push -- "$1 $2"
else
  .config/log warn 'Husky pre-commit hooks are currently not properly setup.'
fi
