---
- name: "Add {{ app_name }}'s apt key"
  apt_key:
    state: present
    url: "{{ brave_apt_key_url }}"

- name: "Add {{ app_name }}'s apt repository"
  apt_repository:
    filename: "{{ app_name | lower | replace(' ', '-') }}"
    repo: "{{ brave_apt_repository }}"
    state: present
    update_cache: true

- name: "Ensure {{ app_name }} is installed"
  apt:
    name: brave-browser
    state: "{{ app_state | default('present') }}"
