---
- name: "Add {{ app_name }}'s rpm key"
  rpm_key:
    key: '{{ brave_key }}'

- name: "Add {{ app_name }}'s yum repository"
  yum_repository:
    baseurl: '{{ brave_baseurl }}'
    description: "{{ app_name }}'s repository"
    gpgcheck: true
    gpgkey: '{{ brave_key }}'
    name: "{{ app_name | lower | replace(' ', '-') }}"
    repo_gpgcheck: true

- name: 'Ensure {{ app_name }} is installed'
  dnf:
    name: brave-browser
    state: "{{ app_state | default('present') }}"
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"
