#!/usr/bin/env bash

cp -rfv /usr/src/dotfiles/dotfiles/.config /usr/src/dotfiles/dotfiles/.local ~/
for i in .bashrc .zshrc .gitconfig .gitattributes
do
  ln -rsfv /usr/src/dotfiles/dotfiles/$i ~/$i
  sudo ln -rsfv /usr/src/dotfiles/dotfiles/$i /root/$i
done

grep -q QT_QPA_PLATFORMTHEME=qt5ct /etc/environment || echo QT_QPA_PLATFORMTHEME=qt5ct | sudo tee -a /etc/environment
sudo cp -rv "$HOME/.local/share/qt5ct" /usr/share
