#!/bin/sh

# @file .config/husky/post-rewrite
# @brief A git hook script for the `post-rewrite` hook. It is called when running commands
#   that rewrite commits (e.g. git pull origin master --rebase)
# @arg $1 Denotes the command it was invoked by: currently one of amend or rebase

if [ -f "$(dirname "$0")/_/husky.sh" ]; then
  . "$(dirname "$0")/_/husky.sh"
  task git:hook:post-rewrite
else
  .config/log warn 'Husky pre-commit hooks are currently not properly setup.'
fi
