---
- name: Ensure openssh-server is installed
  dnf:
    name: openssh-server
    state: present
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"

- name: Ensure fail2ban is installed
  dnf:
    name: fail2ban
    state: present
    enablerepo: epel
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"
  when: install_fail2ban

- name: Run generic Linux tasks
  include_tasks: install-Linux.yml
