---
- name: Ensure .ssh directory exists.
  file:
    dest: ~/.ssh
    mode: 0700
    owner: "{{ user.username }}"
    group: "{{ user.group | default(omit) }}"
    state: directory

- name: Set authorized key
  authorized_key:
    user: "{{ user.username }}"
    state: present
    key: "{{ item }}"
  loop: "{{ user.ssh_authorized_keys }}"
  when: user.ssh_authorized_keys is defined

- name: Copy private keys
  copy:
    src: "{{ item }}"
    dest: "~/.ssh/{{ item | basename }}"
    owner: "{{ user.username }}"
    group: "{{ user.group | default(omit) }}"
    mode: 0600
  loop: "{{ user.ssh_private_keys | default([]) }}"

- name: Copy SSH config
  template:
    src: config.j2
    dest: ~/.ssh/config
    owner: "{{ user.username }}"
    group: "{{ user.group | default(omit) }}"
    mode: 0644

- name: Copy known_hosts
  copy:
    src: known_hosts
    dest: ~/.ssh/known_hosts
    owner: "{{ user.username }}"
    group: "{{ user.group | default(omit) }}"
    mode: 0644
