---
- name: "Ensure {{ app_name }} is installed"
  become: false
  community.general.homebrew:
    name: nvm
    state: "{{ app_state | default('present') }}"

- name: Run Darwin setup tasks
  include_tasks: setup-Linux.yml
  loop: "{{ user_configs }}"
  loop_control:
    label: "{{ user.username }}"
    loop_var: user
  when: (user.system is not defined) or ((user.system is defined) and (not user.system))
