---
- name: Check for existing APCu config files
  ansible.windows.win_find:
    paths: "{{ item }}"
    patterns: '^[\d]*-apc\.ini'
  loop: "{{ php_extension_conf_paths }}"
  register: php_installed_apc_confs

- name: Remove any non-role-supplied APCu config files
  ansible.windows.win_file:
    path: "{{ item.1.path }}"
    state: absent
  when: php_apc_conf_filename != (item.1.path.split('/') | last)
  with_subelements:
    - "{{ php_installed_apc_confs.results }}"
    - files
  notify: restart nginx windows
  loop_control:
    label: "{{ item.1.path }}"

- name: Ensure APCu config file is present # noqa 208
  template:
    src: apc.ini.j2
    dest: "{{ item }}/{{ php_apc_conf_filename }}"
    force: true
  loop: "{{ php_extension_conf_paths }}"
  notify: restart nginx windows
  when: php_enable_apc

- name: Remove APCu config file if APC is disabled
  ansible.windows.win_file:
    path: "{{ item }}/{{ php_apc_conf_filename }}"
    state: absent
  loop: "{{ php_extension_conf_paths }}"
  notify: restart nginx windows
  when: not php_enable_apc
