---
- name: "Add {{ app_name }}'s yum repository"
  yum_repository:
    baseurl: "{{ packer_yum_repo }}"
    description: HashiCorp repository
    gpgcheck: true
    gpgkey: "{{ packer_gpgkey_url }}"
    name: "{{ app_name | lower | replace(' ', '-') }}"

- name: "Ensure {{ app_name }} is installed"
  yum:
    name: packer
    state: present
    update_cache: true
