---
- name: "Ensure {{ app_name }}'s yum repository is added"
  yum_repository:
    baseurl: "{{ gcloud_yum_repo }}"
    description: Google Cloud SDK repository
    gpgcheck: true
    gpgkey: "{{ gcloud_yum_gpg }}"
    name: google-cloud-sdk

- name: "Ensure {{ app_name }} is installed"
  yum:
    name: google-cloud-sdk
    state: "{{ app_state | default('present') }}"
    update_cache: true

- name: "Ensure {{ app_name }}'s optional components are installed"
  yum:
    name: "{{ optional_components }}"
    state: present
  when: optional_components is defined
