---
- name: "Ensure {{ app_name }} is installed"
  chocolatey.chocolatey.win_chocolatey:
    name: gcloudsdk
    state: "{{ app_state | default('present') }}"

- name: "Ensure {{ app_name }}'s optional components are installed" # noqa 503
  ansible.windows.win_command: "gcloud components install {{ component }}"
  loop: "{{ optional_components }}"
  loop_control:
    label: "{{ component }}"
    loop_var: component
  when: optional_components is defined
