---
# Amplify
amplify_rpm_key: https://nginx.org/keys/nginx_signing.key
amplify_baseurl: "http://packages.amplify.nginx.com/centos/7/$basearch"

# Brotli
brotli_dependencies:
  - cmake
  - gcc
  - openssl-devel
  - pcre-devel
  - zlib-devel

# ModSecurity
modsec_dependencies:
  - bison
  - curl
  - curl-devel
  - doxygen
  - flex
  - gcc-c++
  - GeoIP-devel
  - libxml2
  - libxml2-devel
  - lmdb
  - lmdb-devel
  - lua
  - lua-devel
  - ssdeep
  - ssdeep-devel
  - yajl
  - yajl-devel
  - zlib-devel
modsec_waf_conf_directory: /etc/nginx/modsec/owasp-modsecurity-crs

# NGINX
nginx_dependencies:
  - git
  - nginx
  - openssl
  - nginx-mod-http-image-filter
  - nginx-mod-http-xslt-filter
  - nginx-mod-mail
  - nginx-mod-stream
nginx_module_link: /usr/share/nginx/modules
nginx_module_dir: /usr/lib64/nginx/modules
nginx_service_path:
  Fedora: /usr/lib/systemd/system/nginx.service
# @action Fill this chart out with other distros
# @action Include logic for fail case where ansible_distribution is not found

# Miscellaneous
dhparam_path: /etc/ssl/certs/dhparam.pem
error_page_directory: /var/www/html
