#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

. "./.modules/shared/update.lib.sh"

log "Running lint-staged"
npx lint-staged
log "Ensuring Python requirements are installed"
pip3 install -r requirements.txt
log "Checking for files that are too large.."
check-added-large-files
log "Validating Python files.."
check-ast
log "Checking for Python files that do not use literal syntax when initializing empty or zero Python builtin types.."
check-builtin-literals
log "Checking for file names that could possibly cause issues on case-insensitive file systems.."
check-case-conflict
log "Checking for files that place the docstring after code.."
check-docstring-first
log "Checking for non-binary executables that do not have a proper shebang.."
check-executables-have-shebangs
log "Checking for invalid JSON.."
check-json
log "Checking for files with merge conflict strings.."
check-merge-conflict
log "Checking for symlinks that point to nothing.."
check-symlinks
log "Checking for invalid XML.."
check-xml
log "Checking for invalid YML.."
check-yaml
log "Checking for private keys.."
detect-private-key
log "Ensuring requirements.txt is formatted properly"
requirements-txt-fixer requirements.txt
log "Running 'npm run lint'"
npm run lint
log "Checking for spelling errors"
FILES=$(git diff --cached --name-only)
if [ "$FILES" ]; then
  SPELLING_ERRORS=$(npx cspell --no-summary --no-progress --show-context --show-suggestions --no-must-find-files --config ./.modules/shared/.cspell.json $FILES)
  if [ "$SPELLING_ERRORS" ]; then
    echo $SPELLING_ERRORS
    warn "Review the list of possible misspelled words above and correct anything that needs changing."
  else
    success "No spelling errors were found - good job!"
  fi
else
  info "No files staged for spell checking"
fi
success "Successfully passed all validation checks"
