---
- name: "Ensure {{ user.username }}'s ~/Applications folder exists"
  become: true
  become_user: "{{ user.username }}"
  file:
    mode: 0700
    path: ~/Applications
    state: directory

- name: "Copy the {{ app_name }} AppImage from the source location to {{ user.username }}'s Applications folder"
  become: true
  become_user: "{{ user.username }}"
  copy:
    dest: "{{ hyper_user_path }}"
    mode: 0700
    remote_src: true
    src: "{{ hyper_src_path }}"
