---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures Kodi is installed
# Installs Kodi on Archlinux, CentOS, Debian, Fedora, macOS, Ubuntu, and Windows
# @action Ensures Kodi is installed
# Installs MySQL/MariaDB as the database if configured
# @action Ensures Kodi is installed
# Runs MySQL/MariaDB in Docker if configured
# @action Ensures Kodi is configured
# Installs Kodi Addons when a list of addons is provided
# @action Ensures Kodi is configured
# Configures SQL when MySQL/MariaDB is configured to be installed
# @action Ensures Kodi is configured
# Configures Kodi
# @action Ensures Kodi is configured
# Downloads and executes Texture Cache Maintenance Utility
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
