---
description: Test on full desktop VirtualBox images (useful for UAT)
groups:
  Archlinux: Test on Archlinux desktop
  CentOS: Test on CentOS Stream desktop
  Debian: Test on Debian desktop
  Fedora: Test on Fedora desktop
  Ubuntu: Test on Ubuntu desktop
  Windows: Test on Windows desktop
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: task lint:all
platforms:
  - box: Megabyte/Archlinux-Desktop
    cpus: 2
    groups:
      - Archlinux
      - Linux
    memory: 4096
    name: Archlinux-Latest
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: Megabyte/CentOS-Desktop
    cpus: 2
    groups:
      - CentOS
      - Linux
      - RedHat-Flavor
    memory: 4096
    name: CentOS-Stream-8
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: Megabyte/Debian-Desktop
    cpus: 2
    groups:
      - Debian
      - Debian-Flavor
      - Linux
    memory: 4096
    name: Debian-10-Buster
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: Megabyte/Fedora-Desktop
    cpus: 2
    groups:
      - Fedora
      - Linux
      - RedHat-Flavor
    memory: 4096
    name: Fedora-34
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  # Coming soon...
  # - box: Megabyte/macOS-Desktop
  #   cpus: 2
  #   groups:
  #     - macos
  #   memory: 4096
  #   name: macOS-11-Big-Sur
  #   provider_raw_config_args:
  #     - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: Megabyte/Ubuntu-Desktop
    cpus: 2
    groups:
      - Debian-Flavor
      - Linux
      - Ubuntu
    memory: 4096
    name: Ubuntu-21.04-Hirsute-Hippo
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: Megabyte/Windows-Desktop
    cpus: 2
    groups:
      - Windows
    memory: 4096
    name: Windows-10
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
      - "customize [ 'modifyvm', :id, '--natpf1', 'winrm,tcp,127.0.0.1,55985,,5985' ]"
provisioner:
  inventory:
    group_vars:
      all:
        ansible_become_user: ${TEST_USER:-vagrant}
        ansible_password: ${TEST_PASSWORD:-vagrant}
        ansible_user: ${TEST_USER:-vagrant}
        virtualbox_molecule_test: true
      windows:
        ansible_become_method: runas
        ansible_connection: winrm
        ansible_winrm_scheme: http
        ansible_winrm_transport: basic
    host_vars:
      Windows-10:
        ansible_host: 127.0.0.1
        ansible_port: 55985
