---
- name: Construct the URL to download docker-slim archive
  ansible.builtin.set_fact:
    latest_release_url: "{{ 'https://downloads.dockerslim.com/releases/' + docker_slim_version + '/dist_linux.tar.gz' }}"

- name: Download and extract the archive
  ansible.builtin.unarchive:
    src: "{{ latest_release_url }}"
    dest: "{{ dest_path }}"
    remote_src: true
    extra_opts:
      - --strip-components=1
