---
# @action Installs Dockerslim
# Installs Dockerslim on macOS/Linux systems
- name: Fetch the releases page of docker-slim to find the latest version
  ansible.builtin.uri:
    url: "{{ github_repo_url }}/releases"
    return_content: true
  register: docker_slim_releases
  when: ansible_os_family != 'Windows'

- name: Create the regex to filter out versions found in the releases page
  ansible.builtin.set_fact:
    version_regex: "{{ '\/' + github_repo_url.split('/')[4] + '\/tree\/\\S[^\"]*' }}"
  when: ansible_os_family != 'Windows'

- name: Set the version of docker-slim to a variable
  ansible.builtin.set_fact:
    docker_slim_version: "{{ docker_slim_releases.content | regex_search(version_regex) | regex_search('(\\d.){2}.\\d') }}"
  when: ansible_os_family != 'Windows'

- name: Include tasks based on the operating system
  become: true
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Windows'
