---
- name: Import OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install MAAS
  include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure firewall for MAAS
  include_tasks: ufw-debian.yml
  when:
    - ansible_os_family == 'Debian'
    - maas_install_firewall

- name: Ensure Python dependency for managing PostgreSQL is present
  include_tasks: pip.yml

- name: Ensure MAAS database is initialized
  include_tasks: database.yml

- name: Ensure MAAS rack/controller is initialized
  include_tasks: init-maas.yml
