---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  task lint:all
platforms:
  - box: archlinux/archlinux
    cpus: 1
    memory: 512
    name: Archlinux-Latest
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/centos-7
    cpus: 1
    memory: 512
    name: CentOS-7
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/centos-8
    cpus: 1
    memory: 512
    name: CentOS-8
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/centos-stream-8
    cpus: 1
    memory: 512
    name: CentOS-Stream-8
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/debian-9
    cpus: 1
    memory: 512
    name: Debian-9-Stretch
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/debian-10
    cpus: 1
    memory: 512
    name: Debian-10-Buster
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: alvistack/fedora-33
    cpus: 1
    memory: 512
    name: Fedora-33
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: alvistack/fedora-34
    cpus: 1
    memory: 512
    name: Fedora-34
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/ubuntu-18.04
    cpus: 1
    memory: 512
    name: Ubuntu-18.04-Bionic-Beaver
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/ubuntu-20.04
    cpus: 1
    memory: 512
    name: Ubuntu-20.04-Focal-Fossa
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: bento/ubuntu-21.04
    cpus: 1
    memory: 512
    name: Ubuntu-21.04-Hirsute-Hippo
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
  - box: Megabyte/Windows-Desktop
    cpus: 2
    groups:
      - windows
    memory: 4096
    name: Windows-10
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
      - "customize [ 'modifyvm', :id, '--natpf1', 'winrm,tcp,127.0.0.1,55985,,5985' ]"
provisioner:
  inventory:
    group_vars:
      all:
        virtualbox_molecule_test: true
      windows:
        ansible_become_method: runas
        ansible_become_user: vagrant
        ansible_password: vagrant
        ansible_user: vagrant
        ansible_winrm_scheme: http
        ansible_winrm_transport: basic
    host_vars:
      Windows-10:
        ansible_connection: winrm
        ansible_host: 127.0.0.1
        ansible_port: 55985
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: ../converge.vagrant.yml
    prepare: prepare.yml
scenario:
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  create_sequence:
    - dependency
    - create
    - prepare
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
