---
- name: "Ensure Wireguard NetworkManager VPN plugin's dependencies are installed"
  package:
    name: "{{ wireguard_dependencies }}"

- name: "Ensure WireGuard NetworkManager VPN plugin's source is cloned and up-to-date"
  git:
    repo: "{{ wireguard_plugin_repo }}"
    dest: "{{ wireguard_tmp_dir }}"
    depth: "1"
    version: master

- name: "Run ./autogen.sh"
  command: |
    ./autogen.sh --without-libnm-glib
  args:
    chdir: "{{ wireguard_tmp_dir }}"
    creates: "{{ wireguard_tmp_dir }}/configure"

- name: "Run ./configure"
  command: "./configure --without-libnm-glib --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu \
    --libexecdir=/usr/lib/NetworkManager --localstatedir=/var"
  args:
    chdir: "{{ wireguard_tmp_dir }}"
    creates: "{{ wireguard_tmp_dir }}/config.log"

- name: "Run 'make' and 'make install'"
  shell: |
    make
    make install
  args:
    chdir: "{{ wireguard_tmp_dir }}"
    creates: /usr/bin/wg
  notify: restart networkmanager

- name: "Ensure temporary directory for Wireguard files are removed"
  file:
    path: "{{ wireguard_tmp_dir }}"
    state: absent
