---
- name: "Add {{ app_name }}'s yum repository"
  yum_repository:
    baseurl: "{{ azurecli_yum_repo }}"
    description: "{{ app_name }}'s repository"
    gpgcheck: true
    gpgkey: "{{ azurecli_yum_gpg }}"
    name: "{{ app_name | lower | replace(' ', '-') }}"
    repo_gpgcheck: true

- name: "Ensure {{ app_name }} is installed"
  yum:
    name: azure-cli
    state: "{{ app_state | default('present') }}"
    update_cache: true
