---
- name: Register file information for dhparam.pem
  stat:
    path: "{{ dhparam_path }}"
  register: dhparam_pem

- name: Generate dhparam.pem for improved SSL security (this can take awhile..)
  openssl_dhparam:
    path: "{{ dhparam_path }}"
    size: "{{ dhparam_size | default(omit) }}"
  when: not dhparam_pem.stat.exists
