#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/commit-msg
# @brief A git hook script for the `commit-msg` hook
# @arg $1 Path to a temporary file that contains the commit message written by the developer (e.g. .git/COMMIT_EDITMSG)

task git:hook:commit-msg -- "$1"
