#!/usr/bin/env bash

# @file .common/scripts/log.sh
# @brief Logger that logs pretty console messages
# @description
#   This file contains several functions that log content in different formats. The available
#   log functions include:
#
#   * `error` - Logs an error message
#   * `info` - Logs a regular message
#   * `star` - Logs a message with a star icon at the beginning
#   * `success` - Logs a success message
#   * `warn` - Logs a warning message

if [ "${container:=}" != 'docker' ] && type node > /dev/null && [ -f './node_modules/chalk/package.json' ] \
&& [ -f './node_modules/string-break/package.json' ]; then
  echo "Disabled enhanced logging temporarily"
fi

# @description Logs using Node.js
# @example logger info "An informative log"
logger() {
  node .config/scripts/prompts/lib/log.js "$1" "$2"
}

ANSI_STR=""
format() {
  ANSI_STR="$(echo "$1" | sed 's/^\([^`]*\)`\([^`]*\)`/\1\\e[100;1m \2 \\e[0;39m/')"
  if [[ $ANSI_STR == *'`'*'`' ]]; then
    ANSI_STR="$(format "$ANSI_STR")"
  fi
  echo "$ANSI_STR"
}

# @description Logs an error message
# @example .config/log error "Something happened!"
error() {
  if [ -n "$ENHANCED_LOGGING" ]; then
    logger error "$1"
  else
    echo -e "\e[1;31mERROR:\e[0m "$(format "$1")"\e[0;39m"
  fi
}

# @description Logs an info message
# @example .config/log info "Here is some information"
info() {
  if [ -n "$ENHANCED_LOGGING" ]; then
    logger info "$1"
  else
    echo -e "\e[1;36mINFO:\e[0m "$(format "$1")"\e[0;39m"
  fi
}

# @description Logs a message written in markdown
# @example .config/log md "[styled_link](https://google.com)"
# @example .config/log md mymarkdown/file.md
md() {
  if [ -n "$ENHANCED_LOGGING" ]; then
    logger info "$1"
  fi
}

# @description Logs a message that starts with a star emoji
# @example .config/log star "Congratulations"
star() {
  if [ -n "$ENHANCED_LOGGING" ]; then
    logger star "$1"
  else
    echo -e "\e[1;95mSTAR:\e[0m "$(format "$1")"\e[0;39m"
  fi
}

# @description Logs a success message
# @example .config/log success "Yay!"
success() {
  if [ -n "$ENHANCED_LOGGING" ]; then
    logger success "$1"
  else
    echo -e "\e[1;32mSUCCESS:\e[0m "$(format "$1")"\e[0;39m"
  fi
}

# @description Logs a warning message
# @example .config/log warn "Just so you know.."
warn() {
  if [ -n "$ENHANCED_LOGGING" ]; then
    logger warn "$1"
  else
    echo -e "\e[1;33mWARNING:\e[0m "$(format "$1")"\e[0;39m"
  fi
}

if [ -n "$1" ] && [ -n "$2" ]; then
  if [ "$1" == 'warn' ] || [ "$1" == 'success' ] || [ "$1" == 'star' ] || [ "$1" == 'info' ] \
  || [ "$1" == 'error' ]; then
    "$1" "$2"
  fi
fi
