#!/usr/bin/env bash

# @file .common/scripts/log.sh
# @brief Logger that logs pretty console messages
# @description
#   This file contains several functions that log content in different formats. The available
#   log functions include:
#
#   * `error` - Logs an error message
#   * `info` - Logs a regular message
#   * `star` - Logs a message with a star icon at the beginning
#   * `success` - Logs a success message
#   * `warn` - Logs a warning message

if [ "${container:=}" != 'docker' ] && type node > /dev/null && [ -f './node_modules/chalk/package.json' ] \
&& [ -f './node_modules/string-break/package.json' ]; then
  ENHANCED_LOGGING=false
fi

# @description Logs using Node.js
# @example logger info "An informative log"
logger() {
  node .config/scripts/prompts/lib/log.js "$1" "$2"
}

# @description Logs an error message
# @example .config/log error "Something happened!"
error() {
  if [ "$ENHANCED_LOGGING" ]; then
    logger error "$1"
  else
    echo "ERROR: $1"
  fi
}

# @description Logs an info message
# @example .config/log info "Here is some information"
info() {
  if [ "$ENHANCED_LOGGING" ]; then
    logger info "$1"
  else
    echo "INFO: $1"
  fi
}

# @description Logs a message that starts with a star emoji
# @example .config/log star "Congratulations"
star() {
  if [ "$ENHANCED_LOGGING" ]; then
    logger star "$1"
  else
    echo "STAR: $1"
  fi
}

# @description Logs a success message
# @example .config/log success "Yay!"
success() {
  if [ "$ENHANCED_LOGGING" ]; then
    logger success "$1"
  else
    echo "SUCCESS: $1"
  fi
}

# @description Logs a warning message
# @example .config/log warn "Just so you know.."
warn() {
  if [ "$ENHANCED_LOGGING" ]; then
    logger warn "$1"
  else
    echo "WARNING: $1"
  fi
}

if [ -n "$1" ] && [ -n "$2" ]; then
  if [ "$1" == 'warn' ] || [ "$1" == 'success' ] || [ "$1" == 'star' ] || [ "$1" == 'info' ] \
  || [ "$1" == 'error' ]; then
    "$1" "$2"
  fi
fi
