---
- name: "Ensure {{ app_name }}'s dependencies are installed"
  community.general.pacman:
    name: "{{ autojump_dependencies }}"
    state: "{{ app_state | default('present') }}"
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"

- name: "Ensure {{ app_name }}'s source directory is present"
  ansible.builtin.file:
    mode: 0755
    path: "{{ autojump_src_dir }}"
    state: directory

- name: "Ensure {{ app_name }}'s source is cloned and up-to-date"
  ansible.builtin.git:
    dest: "{{ autojump_src_dir }}"
    repo: "{{ autojump_aur_git_repository }}"
  register: autojump_git

- name: Recursively update src directory owner
  file:
    path: "{{ autojump_src_dir }}"
    state: directory
    recurse: true
    owner: "{{ ansible_user | default(lookup('env', 'USER')) }}"

- name: "Remove /usr/bin/autojump if the source files have changed" # noqa 503
  file:
    path: /usr/bin/autojump
    state: absent
  when: autojump_git.changed

- name: "Ensure {{ app_name }} is installed" # noqa 503
  become_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  command: makepkg -sic --noconfirm
  args:
    chdir: "{{ autojump_src_dir }}"
    creates: /usr/bin/autojump
  when: autojump_git.changed
