---
- name: Set systemd-resolved DNS
  lineinfile:
    path: "{{ systemd_resolved_conf_path }}"
    regex: "(^#DNS=|^DNS=)"
    line: "DNS={{ dns_provider }}"
  notify: restart systemd-resolved

- name: Set systemd-resolved FallbackDNS
  lineinfile:
    path: "{{ systemd_resolved_conf_path }}"
    regex: "(^#FallbackDNS=|^FallbackDNS=)"
    line: "FallbackDNS={{ dns_fallback_provider }}"
  when: dns_fallback_provider is defined
  notify: restart systemd-resolved

- name: Set systemd-resolved DNSOverTLS
  lineinfile:
    path: "{{ systemd_resolved_conf_path }}"
    regex: "(^#DNSOverTLS=|^DNSOverTLS=)"
    line: "DNSOverTLS={{ dns_over_tls }}"
  notify: restart systemd-resolved
