---
- name: "Ensure {{ app_name }}'s dependencies are installed"
  community.general.pacman:
    name: "{{ keybase_dependencies }}"
    state: "{{ app_state | default('present') }}"
    update_cache: "{{ omit if skip_package_cache_update is defined else 'true' }}"

- name: "Ensure {{ app_name }}'s source directory is present"
  file:
    mode: 0755
    path: "{{ keybase_src_dir }}"
    owner: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    state: directory

- name: "Ensure {{ app_name }}'s source is cloned and up-to-date"
  become: false
  git:
    dest: "{{ keybase_src_dir }}"
    repo: "{{ keybase_aur_git_repository }}"
    version: master
  register: keybase_git

- name: "Remove /usr/sbin/keybase if the source files have changed" # noqa 503
  file:
    path: /usr/sbin/keybase
    state: absent
  when: keybase_git.changed

- name: "Ensure {{ app_name }} is installed"
  become: false
  command: makepkg -sic --noconfirm
  args:
    chdir: "{{ keybase_src_dir }}"
    creates: /usr/sbin/keybase

- name: Ensure setting to disable root redirector exists
  copy:
    dest: /etc/keybase/config.json
    content: |
      {
        "disable-root-redirector": true
      }
    mode: 0644

- name: "Ensure keybase-redirector permissions are updated"
  file:
    path: /usr/bin/keybase-redirector
    mode: a-s
    state: file
