---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Darwin'

# @action Ensures AutoHotKey is installed
# Installs AutoKey on Archlinux, CentOS, Debian, Fedora and Ubuntu
# @action Ensures AutoHotKey is installed
# Installs AutoHotKey on Windows
# @action Ensures AutoHotKey is installed
# Installs AutoKey and AutoHotKey scripts
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user | default(ansible_env.USERNAME) if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Darwin'
