---
- name: "Ensure {{ app_name }} is installed"
  community.general.snap:
    name: chromium
    state: "{{ app_state | default('present') }}"

- name: Determine whether or not GNOME is installed
  stat:
    path: /usr/bin/gnome-session
  register: gnome_session

- name: Ensure chrome-gnome-shell is installed
  package:
    name: chrome-gnome-shell
    state: "{{ app_state | default('present') }}"
  when: gnome_session.stat.exists
