---
- name: Configure remote host entries
  win_lineinfile:
    path: "{{ windows_hosts_path }}"
    regexp: "{{ hosts[item.key].regexp }}"
    line: "{{ hosts[item.key].ip_address }} {{ hosts[item.key].hosts }} {{ hosts[item.key].regexp }}"
    state: present
  when: item.key not in (apps | default([]))
  loop: "{{ lookup('dict', hosts) }}"
  loop_control:
    label: "{{ item.key }}"

- name: Configure local host entries
  win_lineinfile:
    dest: "{{ windows_hosts_path }}"
    regexp: "{{ hosts[item.key].regexp }}"
    line: "127.0.0.1 {{ hosts[item.key].hosts }} {{ hosts[item.key].regexp }}"
    state: present
  when: item.key in (apps | default([]))
  loop: "{{ lookup('dict', hosts) }}"
  loop_control:
    label: "{{ item.key }}"
