---
- name: 'Ensure {{ app_name }} and npm are installed'
  become: false
  community.general.homebrew:
    name: "node{{ node_version | regex_replace('.x', '') }}"
    state: present

- name: Ensure npm_config_prefix bin is added to $PATH
  include_tasks: user-Darwin.yml
  loop: '{{ user_configs }}'
  loop_control:
    label: '{{ user.username }}'
    loop_var: user

- name: Run common Linux tasks
  include_tasks: install-Linux.yml
