#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/pre-push
# @brief A git hook script for the `pre-push` hook
# @arg $1 The name of the remote (e.g. origin)
# @arg $2 The location of the remote (e.g. git@gitlab.com:megabyte-labs/common/angular.git)

task git:hook:pre-push
