#!/bin/sh

# @file .config/husky/commit-msg
# @brief A git hook script for the `commit-msg` hook
# @arg $1 Path to a temporary file that contains the commit message written by the developer (e.g. .git/COMMIT_EDITMSG)

[ -f .config/log ] && chmod +x .config/log
if [ -f "$(dirname "$0")/_/husky.sh" ]; then
  . "$(dirname "$0")/_/husky.sh"
  type task &> /dev/null && task git:hook:commit-msg -- "$1"
else
  .config/log warn 'Husky pre-commit hooks are currently not properly setup.'
fi
