#!/bin/sh
# @file .config/husky/post-commit
# @brief A git hook script for the `post-commit` hook. There are no parameters but you can easily get the
#   last commit by running `git log -1 HEAD`. Generally, this script is used for notifications or something similar.

[ -f .config/log ] && chmod +x .config/log
if [ -f "$(dirname "$0")/_/husky.sh" ]; then
  . "$(dirname "$0")/_/husky.sh"
  type task &> /dev/null && task git:hook:post-commit
else
  .config/log warn 'Husky pre-commit hooks are currently not properly setup.'
fi
