#!/bin/sh

# @file .config/husky/post-merge
# @brief A git hook script for the `post-merge` hook
# @arg $1 A status flag specifying whether or not the merge being done was a squash merge

[ -f .config/log ] && chmod +x .config/log
if [ -f "$(dirname "$0")/_/husky.sh" ]; then
  . "$(dirname "$0")/_/husky.sh"
  type task &> /dev/null && task git:hook:post-merge
else
  .config/log warn 'Husky pre-commit hooks are currently not properly setup.'
fi
