#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/post-commit
# @brief A git hook script for the `post-commit` hook. There are no parameters but you can easily get the
#   last commit by running `git log -1 HEAD`. Generally, this script is used for notifications or something similar.

task git:hook:post-commit
