#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# @file .config/husky/post-checkout
# @brief A git hook script for the `post-checkout` hook

echo "[debug] post-checkout - param 1: $1"
echo "[debug] post-checkout - param 2: $2"
echo "[debug] post-checkout - param 3: $3"
echo "[debug] post-checkout - param 4: $4"
echo "[params] $GIT_PARAMS"
task git:hook:post-checkout
