#!/bin/sh

# @file .config/husky/post-merge
# @brief A git hook script for the `post-merge` hook
# @arg $1 A status flag specifying whether or not the merge being done was a squash merge

[ -f .config/log ] && chmod +x .config/log
if [ -f "$(dirname "$0")/_/husky.sh" ]; then
  . "$(dirname "$0")/_/husky.sh"

  # Attempt to register Bodega/Task from common places if it is not in PATH
  if ! type task &> /dev/null && [ -f "$HOME/.profile" ]; then
    . "$HOME/.profile"
  elif ! type task &> /dev/null; then
    PATH="$PATH:$HOME/.local/go/bin:$HOME/.local/bin:$HOME/bin:$HOME/go/bin"
  fi

  # Show warning if Bodega/Task is still not registered/installed, else proceed with hook
  if ! type task &> /dev/null; then
    .config/log warn 'Bodega `task` does not appear to be installed or is not registered in the `PATH` variable - please manually include it'
    .config/log info 'Get Bodega here -> `https://github.com/megabyte-labs/Bodega`'
  else
    task git:hook:post-merge
  fi
else
  .config/log warn 'Husky pre-commit hooks are currently not properly setup.'
fi
