---
- name: Include variables based on the operating system
  include_vars: "{{ ansible_os_family }}.yml"

# @action Ensures Nginx is installed
# Installs Nginx on Archlinux, CentOS, Debian, Fedora, Ubuntu, MacOS and Windows
# @action Ensures Nginx is configured
# Sets up custom status pages if configured
# @action Ensures Nginx is configured
# Generates DHparam files for improved SSL security
# @action Ensures Nginx is configured
# Clears default sites-available configuration settings if configured
# @action Ensures Nginx is configured
# Clears default sites-enabled configuration settings if configured
# @action Ensures Nginx is configured
# Generates sites-available configuration settings for the provided applications
# @action Ensures Nginx is configured
# Restarts Nginx Service for the changes to take effect
- name: Include tasks based on the operating system
  become: true
  become_method: "{{ 'runas' if ansible_os_family == 'Windows' else 'sudo' }}"
  become_user: "{{ ansible_user if ansible_os_family == 'Windows' else omit }}"
  block:
    - include_tasks: "install-{{ ansible_os_family }}.yml"
