---
description: Run the play remotely via SSH
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: ssh
      ansible_host: ${TEST_HOST}
      ansible_port: ${TEST_PORT:-22}
      ansible_ssh_user: ${TEST_SSH_USER:-ansible}
platforms:
  - instance
provisioner:
  connection_options:
    ansible_password: ${TEST_PASSWORD:-ansible}
    ansible_user: ${TEST_USER:-ansible}
scenario:
  create_sequence:
    - dependency
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - prepare
    - converge
    - check
  converge_sequence:
    - dependency
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
  test_sequence:
    - dependency
    - lint
    - cleanup
    - syntax
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
